spring:
  profiles:
    active: dev

google:
  application-name: Google API Client
  domain: the.google.workspace
  admin: administrator@the.google.workspace
  json-credential: classpath:/META-INF/credentials/key.json
  scopes:
    - https://www.googleapis.com/auth/admin.directory.user
    - https://www.googleapis.com/auth/admin.directory.group
    - https://www.googleapis.com/auth/admin.directory.group.member
    - https://www.googleapis.com/auth/admin.directory.user.readonly
    - https://www.googleapis.com/auth/admin.reports.usage.readonly
    - https://www.googleapis.com/auth/admin.reports.audit.readonly
  default-organizational-unit: /
  enable-writing: false
